const en = {
  inputALB: {
    placeholder: '',
  },
  localization: {
    deviceLanguage: 'en-US',
  },
  login: {
    title: 'Login',
    tabUserCode: 'User Code',
    tabTCKN: 'TCKN',
    tabCardNo: 'Card No',
    usernamePlaceholder: 'Username',
    passwordPlaceholder: 'Password',
    loginButton: 'Login',
    userTCKN: 'TC Number',
    userTCKNPassword: 'Password',
    cardNumber: 'Card Number',
    phoneNumber: 'Phone Number',
    cardPassword: 'Card Password',
    company: 'Company',
    customerNoTCKN: 'Customer No/TC',
    password: 'Password',
    personal: 'Personal',
    corporate: 'Corporate',
    alreadyLoggedIn: 'This user is already signed in.',
    forgotPassword: 'Forgot Password',
    help: 'Help',
    pinCreation: {
      continue: 'Continue',
      pin: 'Pin',
      confirmPin: 'Confirm Pin',
      title: 'PIN Creation',
    },
    pinLogin: {
      title: 'Confirmation with Pin',
      description: 'You can continue with pin code',
      pin: 'Pin',
      remember: 'Remember',
      continue: 'Continue',
    },
    smsConfirmation: {
      title: 'SMS Password Confirmation',
      smsPassword: 'SMS Password',
      description: 'In order to confirm, enter the password sent to your mobile phone ',
      confirm: 'Confirm',
      resend: 'Resend',
    },
    securityImage: {
      title: 'Security Image',
    },
    securityImageLogin: {
      title: 'Login with Security Image',
      securityImage: 'Security Image',
      securityImageText: 'Your one time password is sent to your mobile phone number via SMS.',
      description: 'In order to confirm, enter the password sent to your mobile phone ',
      smsPassword: 'SMS Password',
      confirm: 'Confirm',
      resend: 'Resend',
    },
    changePassword: {
      continue: 'Continue',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      title: 'Internet / Mobile Branch Password Reset',
      firstCondition: 'It can be a minimum of 6 and a maximum of 32 characters.',
      secondCondition:
        'It can contain both letters and numbers. It can only consist of numbers. It should not consist solely of letters.',
      thirdCondition:
        'Password must not contain any easily guessable personal information such as date of birth, name and surname.',
      fourthCondition: 'There should not be 4 consecutive (1234-abcç) and repeating (1111-aaaa) characters.',
      fifthCondition: 'It must be different from your last three password.',
    },
  },
  otpActivate: {
    title: 'Pin Activation',
    pinPlaceholder: 'Pin',
    pin2Placeholder: 'Confirm Pin',
    activationButton: 'Activate',
    confirmedPinMessage: 'Pin was already set!',
  },
  account: {
    title: 'My Accounts',
    allAccount: 'All',
    specialPrevalentAccount: 'Special Prevalent Account',
    participationAccount: 'Participation Account',
    depositAccount: 'Deposit Account',
    balance: 'Balance',
    accountDate: 'Account Date',
    accountList: {
      accountActivities: 'Account Activities',
      accountInfo: 'Account Info',
      shareIBAN: 'Share IBAN',
      changeAccountName: 'Change Account Name',
      segmentTL: 'Turkish Lira',
      segmentOther: 'Other',
      search: 'Search account...',
      actions: {
        addFavorite: 'Add to Favorites',
        removeFavorite: 'Remove from Favorites',
        accountInfo: 'Account Information',
        accountTransactions: 'Account Transactions',
        shareIban: 'Share IBAN',
      },
      noAccount: {
        current: {
          messageHeader: "You don't have any current accounts.",
          messageText: 'You can open a new current account in 1 minute.',
          infoHeader: 'What are the advantages of a current account?',
          infoText:
            'You can lorem ve ipsum with exchange accpunts and simply dummy text of the printing and typesetting industry with these accounts.',
          open: 'Open Current Account',
        },
        participation: {
          messageHeader: 'You do not have a participation account.',
          messageText: 'You can open a participation account in less than 1 minute.',
          infoHeader: 'What are the benefits of  participation accounts?',
          infoText:
            'With advantageous profit share ratios, you can open an account immediately and start saving for the future. ',
          open: 'Open Participation Account',
        },
      },
    },
    allAvailableBalance: 'All Available Balance',
    popOverBalance: 'Total available balance is shown by calculating the amount of USD and EUR amount.',
  },
  base: {
    footerTabHomePage: 'Homepage',
    footerTabTransactions: 'Transactions',
    footerTabAccounts: 'Accounts',
    footerTabCards: 'Cards',
    footerTabProducts: 'Products',
    footerTabCampaigns: 'Campaigns',
  },
  otpGenerate: {
    title: 'Generate OTP',
    pinPlaceholder: 'Pin',
    pinValidateButton: 'Generate OTP',
    unsetPinMessage: 'Pin was not set before!',
  },
  otp: {
    pin: 'Pin',
    validateButton: 'Validate',
    otp: 'OTP',
  },
  maps: {
    title: 'Atm/Branch Finder',
    segmentAll: 'All',
    segmentAtm: 'ATM',
    segmentBranch: 'Branch',
    errorOccured: 'An error occured!',
    atm: 'Atm',
    branchName: 'Branch Name',
    anErrorOccured: 'We cannot proceed this process because of an error in our system. Please try again later.',
  },

  smsConfirmation: {
    title: 'SMS Password Confirmation',
    smsPassword: 'SMS Password',
    description: 'In order to confirm, enter the password sent to your mobile phone ',
    confirm: 'Confirm',
    resend: 'Resend',
  },
  userHome: {
    title: 'Home',
    quickActions: 'Quick Actions',
    recentExpenses: 'Recent Expenses',
    all: 'All',
    specialOffers: 'Special Offers For You',
    yourRecentExpenses: 'Your Recent Expenses',
    adHousing: "Don't miss the chance of housing financement up to 5% benefit rates",
    adStore: 'Up to 30% sales at Beymen stores',
  },

  calculation: {
    calculate: 'Calculate',
    sellBuy: 'Buy / Sell',
    lastUpdatedDate: 'Last Updated Date',
  },
  dateRange: {
    startDate: 'Starting date',
    endDate: 'Ending date',
  },
  filter: {
    title: 'Detailed Search',
    operationAmount: 'Operation Amount',
    moneyIntervalLeast: 'Min. Amount',
    moneyIntervalMost: 'Max. Amount',
    operationType: 'Transaction Type',
    chooseOperationType: 'Choose Transaction Type..',
    operationChannel: 'Transaction Channel',
    chooseOperationChannel: 'Choose Transaction Channel..',
    chooseCashFlow: 'Choose Cash Flow..',
    cashflow: 'Cash Flow',
    operationExplanation: 'Transaction Explanation',
    applyFilter: 'Apply Filter',
  },

  accountType: {
    allName: 'All',
    current: 'Current',
    currentAccount: 'Current Account',
    export: 'Export',
    exportAccount: 'Export Account',
    participation: 'Participation',
    participationAccount: 'Participation Account',
  },
  error: {
    systemError: 'Please again try later',
    sessionExpired: 'Session Exprired.',
  },
  common: {
    ok: 'Okay',
  },
  validation: {
    invalidCustomerNo: 'Invalid customer  no',
    invalidAccountName: 'Invalid account name',
    nonZeroMoney: 'Money value should be greater than zero',
  },
  validationError: {
    required: 'Required Area',
  },
  help: {
    title: 'Help',
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    mobileBranchPromotion: 'Mobile Branch Promotion',
    followAlbaraka: 'Follow Albaraka',
  },
  notificationList: {
    delete: 'Delete',
  },
};

export default en;
