const tr = {
  inputALB: {
    placeholder: '',
  },
  localization: {
    deviceLanguage: 'tr',
  },
  applications: {
    esb: 'ESB',
    actman: 'Activite Yönetimi',
    notification: 'Notification',
  },
  login: {
    title: 'Giriş',
    tabUserCode: 'Müşteri No ile Giriş',
    tabTCKN: 'TCKN ile Giriş',
    tabCardNo: 'Kartlı Giriş',
    usernamePlaceholder: 'Müşteri Numaranız',
    passwordPlaceholder: 'Şifreniz',
    loginButton: 'Giriş',
    userTCKN: 'TC Kimlik No',
    userTCKNPassword: 'Şifreniz',
    cardNumber: 'Kart Numaranız',
    phoneNumber: 'Cep Telefon Numaranız',
    cardPassword: 'Kart Şifreniz',
    company: 'Kurum',
    customerNoTCKN: 'Müşteri No/TCKN',
    password: 'Parola',
    personal: 'Bireysel',
    corporate: 'Kurumsal',
    alreadyLoggedIn: 'Bu kullanıcı giriş yapmıştır.',
    forgotPassword: 'Şifremi Unuttum',
    help: 'Yardım',
    pinCreation: {
      continue: 'Devam',
      pin: 'Pin',
      pinConfirm: 'Pin (Tekrar)',
      title: 'PIN Belirleme',
    },
    pinLogin: {
      title: 'Pin Girişi ile Onay',
      description: 'Pin girişi ile devam edebilirsiniz.',
      descriptionWithImage: 'Güvenlik resminizi onaylıyorsanız Pin girişi ile devam edebilirsiniz.',
      pin: 'Pin',
      remember: 'Hatırla',
      continue: 'Devam',
    },
    smsConfirmation: {
      title: 'SMS Şifre ile Onay',
      smsPassword: 'SMS Şifre',
      description: ' numaralı telefonunuza gönderilen SMS şifresini onaylamak için giriniz:',
      confirm: 'Onayla',
      resend: 'Tekrar Gönder',
    },
    securityImage: {
      title: 'Güvenlik Resmi',
    },
    securityImageLogin: {
      title: 'Güvenlik Resmi ile Giriş',
      securityImage: 'Güvenlik Resmi',
      securityImageText: 'Tek kullanımlık şifreniz, aşağıdaki cep telefonu numaranıza SMS ile gönderilmiştir.',
      description: ' numaralı telefonunuza gönderilen SMS şifresini onaylamak için giriniz:',
      smsPassword: 'SMS Şifre',
      confirm: 'Onayla',
      resend: 'Tekrar Gönder',
    },
    securityImageConfirmation: {
      title: 'Güvenlik Resmi Onay',
      continue: 'Devam',
      confirmationText: 'Güvenlik resminizi onaylıyorsanız devam edebilirsiniz.',
    },
    changePassword: {
      continue: 'Devam',
      currentPassword: 'Mevcut Şifre',
      newPassword: 'Yeni Şifre',
      confirmNewPassword: 'Yeni Şifre (Tekrar)',
      title: 'İnternet / Mobil Şube Şifre Değişikliği',
      firstCondition: 'En az 6 en fazla 32 karakterden oluşabilir.',
      secondCondition:
        'Hem harf hem rakam içerebilir. Sadece rakamlardan oluşabilir. Yalnızca harflerden oluşmamalıdır.',
      thirdCondition: 'Ad soyad, doğum tarihi gibi kolay tahmin edilebilir kişisel bilgiler içermemelidir.',
      fourthCondition:
        'Art arda 4 hane ve üstü ardışık(1234-abcç) ve tekrar eden (1111-aaaa) karakterler bulunmamalıdır.',
      fifthCondition: 'Son üç şifrenizden farklı olmalıdır.',
    },
  },
  otpActivate: {
    title: 'Pin Aktivasyon',
    pinPlaceholder: 'Pin',
    pin2Placeholder: 'Pini Doğrula',
    activationButton: 'Aktive Et',
    confirmedPinMessage: 'Pin was already set!',
  },
  account: {
    title: 'Hesaplarım',
    allAccount: 'Tümü',
    specialPrevalentAccount: 'Özel Cari Hesap',
    participationAccount: 'Katılma Hesabı',
    depositAccount: 'Vadeli Hesap',
    balance: 'Bakiye',
    accountDate: 'Hesap Tarihi',
    search: 'Hesap ara...',
    accountList: {
      accountActivities: 'Hesap Hareketleri',
      accountInfo: 'Hesap Bilgileri',
      shareIBAN: 'IBAN Paylaş',
      changeAccountName: 'Hesap Adı Değiştir',
      segmentTL: 'Türk Lirası',
      segmentOther: 'Diğer',
      actions: {
        addFavorite: 'Favorilerime Ekle',
        removeFavorite: 'Favorilerimden Çıkar',
        accountInfo: 'Hesap Bilgileri',
        accountTransactions: 'Hesap Hareketleri',
        shareIban: 'IBAN Paylaş',
      },
      noAccount: {
        current: {
          messageHeader: 'Herhangi bir cari hesabınız bulunmamaktadır.',
          messageText: '1 dakikadan kısa sürede bir hesap açabilirsiniz.',
          infoHeader: 'Carı Hesapların faydaları neler?',
          infoText:
            'Döviz hesapları ile lorem ve ipsum yapabilir ardından  bunları simply dummy text of the printing and typesetting  industry.',
          open: 'Cari Hesap Aç',
        },
        participation: {
          messageHeader: 'Katılma hesabınız bulunmamaktadır.',
          messageText: '1 dakikadan daha kısa bir sürede katılma hesabı açabilirsiniz.',
          infoHeader: 'Katılma hesabının faydaları nelerdir?',
          infoText:
            'Avantajlı kâr payı oranlarıyla anında katılma hesabı açabilir, geleceğiniz için birikim yapmaya bugünden başlayabilirsiniz.',
          open: 'Katılma Hesabı Aç',
        },
      },
    },
    allAvailableBalance: 'Tüm Kullanılabilir Bakiye',
    popOverBalance: 'Tüm kullanılabilir bakiyenin USD ve EUR tutar karşılığı hesaplanarak gösterilmektedir.',
  },
  base: {
    footerTabHomePage: 'Ana Sayfa',
    footerTabTransactions: 'İşlem',
    footerTabAccounts: 'Hesaplar',
    footerTabCards: 'Kartlar',
    footerTabProducts: 'Ürün',
    footerTabCampaigns: 'Kampanya',
    footerTabAssistant: 'Asistan',
    footerTabSettings: 'Ayarlar',
  },
  customerService: {
    title: 'Müşteri Hizmetleri',
    phoneNumber: '444 5 666',
  },
  otpGenerate: {
    title: 'OTP Oluşturma',
    pinPlaceholder: 'Pin',
    pinValidateButton: 'Generate OTP',
    unsetPinMessage: 'Pin was not set before!',
  },
  otp: {
    pin: 'Pin',
    validateButton: 'Doğrula',
    otp: 'OTP',
  },
  maps: {
    title: 'Atm/Şube Bulucu',
    segmentAll: 'Hepsi',
    segmentAtm: 'ATM',
    segmentBranch: 'Şube',
    errorOccured: 'Bir hata oluştu!',
    atm: 'Bankamatik',
    branchName: 'Şube Adı',
    anErrorOccured:
      'Sistemimizde oluşan bir hatadan dolayı işleminizi gerçekleştiremiyoruz. Lütfen daha sonra tekrar deneyiniz.',
  },
  userHome: {
    title: 'Anasayfa',
    quickActions: 'Hızlı İşlemler',
    recentExpenses: 'Son Harcamalar',
    all: 'Tümü',
    specialOffers: 'Sana Özel Fırsatlar',
    yourRecentExpenses: 'Son Harcamalarınız',
    adHousing: '%5 kar oranı ile en uygun konut finansmanı fırsatını kaçırmayın',
    adStore: "Beymen mağazalarında %30'a varan indirimler",
  },
  calculation: {
    calculate: 'Hesapla',
    sellOrBuy: 'Döviz Al / Sat',
    lastUpdatedDate: 'Kurlara ait son güncelleme : ',
    thousandsSeperator: '.',
    decimalSeperator: ',',
    currencyValue: 'Döviz Tutarı',
    currencyType: 'Döviz Tipi',
    currencyCalculationPage: 'Döviz Hesaplama Sayfası',
  },
  dateRange: {
    startDate: 'Baslangıç tarihi',
    endDate: 'Bitiş tarihi',
  },
  filter: {
    title: 'Detaylı Arama',
    operationAmount: 'İşlem Miktarı',
    moneyIntervalLeast: 'En Az Tutar',
    moneyIntervalMost: 'En Fazla Tutar',
    operationType: 'İşlem Tipi',
    chooseOperationType: 'İşlem Tipi Seçiniz..',
    operationChannel: 'İşlem Kanalı',
    chooseOperationChannel: 'İşlem Kanalı Seçiniz..',
    chooseCashFlow: 'Nakit Akışını Seçiniz..',
    cashflow: 'Nakit Akışı',
    operationExplanation: 'İşlem Açıklaması',
    applyFilter: 'Filtreyi Uygula',
  },
  error: {
    systemError: 'Please again try later',
    sessionExpired: 'Session Exprired.',
  },
  common: {
    ok: 'Tamam',
  },
  validation: {
    invalidCustomerNo: 'Geçersiz müşteri numarası',
    invalidAccountName: 'Geçersiz Hesap Adı',
    nonZeroMoney: 'Para değeri 1 birimden büyük bir değer olmalıdır.',
    iban: 'Geçersiz Iban Numarası',
    pickerRequired: 'Lütfen belirtilen alandan seçim yapınız',
    maxLength: 'Girilen Değer maxiumum alan sayısını geçti',
    minLength: 'Girilen Değer minumum alan sayısının altında kaldı',
    isRepetitation: 'Girilen değerde art arda 4 hane ve üstü tekrar eden karakterler bulunmamalıdır',
    isSequential: 'Girilen değerde art arda 4 hane ve üstü ardışık karakterler bulunmamalıdır',
    isContainsLetter: 'Girilen değerde en az 1 adet harf olmalıdır',
    isContainsNumber: 'Girilen değerde en az 1 adet rakam olmalıdır',
    hasLowerCase: 'Girilen değerde en az 1 adet küçük harf olmalıdır',
    hasUpperCase: 'Girilen değerde en az 1 adet büyük harf olmalıdır',
    hasOnlyLetters: 'Girilen değer yalnızca harflerden oluşmamalıdır.',
    onlyNumericPassword: 'Şifre sadece sayısal değerlerden oluşmalıudır.',
    password4Charecter: 'Şifre 4 haneden oluşmalıdır',
    password1990_2000: 'Şifre 1990 ile 2000 arasında olmamalıdır',
    passwordMin8character: 'Şifre minumum 8 haneden oluşmalıdır.',
    moneyUndefined: 'Para değeri 1 birimden büyük bir değer olmalıdır.',
  },
  validationError: {
    required: 'Zorunlu Alan',
  },
  help: {
    title: 'Yardım',
    frequentlyAskedQuestions: 'Sık Sorulan Sorular',
    mobileBranchPromotion: 'Mobil Şube Tanıtım',
    followAlbaraka: 'Albaraka yı Takip Edin',
  },
  notificationList: {
    delete: 'Sil',
  },
};

export default tr;
